name: Deploy Shiny App

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  pull_request:
    branches:
      - main  # Adjust branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build . -t my-shiny-app

      - name: Run Docker container
        run: docker run -d -p 3838:3838 my-shiny-app
